### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by saforem2**

### CODE REVIEW

**Comment by janosh** [comment]
Thanks, could you briefly explain how you're using normalizing flows?

Also, I should mention that the paper section of this repo is for peer-reviewed papers only. Are you planning to submit?

Lastly, I noticed clicking on the link to your poster (https://github.com/saforem2/l2hmc-qcd/blob/main/bit.ly/l2hmc_poster)  in [your readme](https://github.com/saforem2/l2hmc-qcd#readme) is giving a 404.

**Comment by saforem2** [comment]
> Thanks, could you briefly explain how you're using normalizing flows?

Sure, sorry!

So the main idea is that we can introduce a collection of functions (implemented as normalizing flows) into the molecular dynamics update of the Hamiltonian Monte Carlo algorithm.

Normalizing flows are an obvious choice for these functions due to their invertibility and tractable log Jacobian.

These flows can then be trained in such a way that encourages our sampler to effectively explore the target distribution, resulting in a (generally) more efficient sampling technique.

> Also, I should mention that the paper section of this repo is for peer-reviewed papers only. Are you planning to submit?

So, our initial work (https://arxiv.org/abs/2105.03418) was submitted and accepted as a contribution to the [Deep Learning for Simulation](https://simdl.github.io/cfp/) workshop at ICLR 2021, which although _technically_ reviewed, I guess wouldn't necessarily be classified as having been _peer reviewed_ in the traditional sense.

We do plan to submit an expanded, detailed submission which will be conventionally peer reviewed sometime in the near future, but I can't say with certainty when that will happen. 

I apologize though for not having been aware of the peer-reviewed requirement for this section, and am completely understanding if you choose not to include our work.

> Lastly, I noticed clicking on the link to your poster (https://github.com/saforem2/l2hmc-qcd/blob/main/bit.ly/l2hmc_poster) in your readme is giving a 404.

Thank you for noticing that, I've hopefully updated the link now.

**Comment by janosh** [comment]
> These flows can then be trained in such a way that encourages our sampler to effectively explore the target distribution, resulting in a (generally) more efficient sampling technique.

Out of curiosity, could you elaborate on this? I still don't understand how the normalizing flows are leveraged.

Is the paper targeted mostly at physicists? Besides some references to flow papers, normalizing flows don't appear to get mentioned in your manuscript.

> We do plan to submit an expanded, detailed submission which will be conventionally peer reviewed sometime in the near future, but I can't say with certainty when that will happen.

That's great! Perhaps we can reopen this issue once that's done?

> I apologize though for not having been aware of the peer-reviewed requirement for this section, and am completely understanding if you choose not to include our work.

Hardly your fault. I didn't exactly make this clear anywhere in the readme. 😅  Will add a sentence at the bottom as well as a PR template.

**Comment by saforem2** [comment]
> Out of curiosity, could you elaborate on this? I still don't understand how the normalizing flows are leveraged.

Sure, sorry! So the original idea was proposed here

https://arxiv.org/abs/1711.09268

but the main idea is that we can augment the `x` and `v` updates in the leapfrog integrator with these auxiliary functions which are parameterized by RealNVP coupling layers. 

This generalized leapfrog integrator then takes as input `x, v` and uses these invertible coupling layers ("normalizing flows") to construct a trajectory, eventually generating the proposal configurations `x', v'`. 

We then construct a loss that depends on the difference between `x` and `x'` which is then optimized during training.

I guess it's not a purely generative approach as is typical for normalizing flows, but it makes use of the RealNVP architecture which is (from my understanding) really the basis of all these normalizing flow type approaches.

> Is the paper targeted mostly at physicists? Besides some references to flow papers, normalizing flows don't appear to get mentioned in your manuscript.

Our initial experiments (https://arxiv.org/abs/2105.03418) are focused exclusively on looking at applying this approach to lattice gauge models, but our approach is generally applicable and works with any target distribution.

> > We do plan to submit an expanded, detailed submission which will be conventionally peer reviewed sometime in the near future, but I can't say with certainty when that will happen.
>
> That's great! Perhaps we can reopen this issue once that's done?

yeah, no worries! I'll make sure to follow up then!

**Pull request closed without merging**
