### PR TITLE
JAX package and papers

### LINKED ISSUE #65: Unlisted JAX package and paper
- [flowMC](https://github.com/kazewong/flowMC): Normalizing-flow enhanced sampling package for probabilistic inference
- [Efficient Bayesian Sampling Using Normalizing Flows to Assist Markov Chain Monte Carlo Methods](https://openreview.net/pdf?id=mvtooHbjOwx)
- [Adaptive Monte Carlo augmented with normalizing flows](https://www.pnas.org/doi/10.1073/pnas.2109420119)

### PR DESCRIPTION
**Pull request by Qazalbash**
fixes #65.

### CODE REVIEW

**Comment by Qazalbash** [comment]
@janosh you can merge it!

**Comment by janosh** [comment]
let's just add everything in 1 PR. not large enough to split imo

**Comment by Qazalbash** [comment]
Done from my side!

**Review by janosh — APPROVED** [review]
thanks @Qazalbash, very nice additions! 👍

**Pull request merged**
